project:
  type: website

website:
  title: "Joe Deegan"
  search: false

format:
  html:
    theme: none
    template: html.template
    css: styles.css
    backgroundcolor: "#fefefe"
    title-block-style: plain
    title: none
    anchor-sections: false
    minimal: true

    
editor: source

