<link rel="preconnect" href="https://fonts.googleapis.com"> <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> <link href="https://fonts.googleapis.com/css2?family=Geist:wght@100..900&display=swap" rel="stylesheet">

---
title: "Joe Deegan"
---

# Joe Deegan

I am an Irish doctor working as a specialty registrar in public health medicine in the UK.

I'm interested in evaluation, operational research, and design thinking in healthcare. I completed my medical degree in Trinity College Dublin, and my MSc in Public Health at the London School of Hygiene and Tropical Medicine.

I'm currently working as part of the public health team at Kent County Council.

Before this, I worked in acute medicine in St James's Hospital, Dublin. I was the lead NCHD at St James's Hospital in 2022-2023, and received a George Moore Scholarship from the Ireland's Funds to study public health in London.

If you'd like to chat to me about my work or anything at all, please get in touch! You can find me on [LinkedIn](https://www.linkedin.com/in/deeganjoe/) or [Bluesky](https://www.joedeegan.bsky.social).

## Some Projects

Here are a few projects I've worked on over the last while that I'm really proud of. I've written a small piece about each of them.

<table>
<tr>
  <td>Sept 2024</td>
  <td>&emsp;</td>
  <td>[MSc Dissertation](/posts/msc-dissertation/index.qmd)</td>
</tr>
<tr>
  <td>Aug 2023</td>
  <td>&emsp;</td>
  <td>[Lead NCHD/ NCHD Handbook](/posts/lead-nchd/index.qmd)</td>
</tr>
</table>

## The Problem of Leisure

It's always nice to get a fuller picture of someone than a CV can provide. Here's a few things I've enjoyed over the last little while.

I've been listening to Lankum, Romy, Charli XCX, Bonnie Prince Billy, and the Nolan Sisters.

I've been reading Intermezzo by Sally Rooney, Say Nothing by Patrick Radden Keefe, and The Wren, The Wren by Anne Enright. I still haven't been able to get Prophet Song by Paul Lynch out of my head.

The best movies I watched in 2024 were Challengers, Conclave, and American Fiction. (I also quite liked The Substance).

## A Bit of Previous

<table>
<tr>
  <td>2024 to now</td>
  <td>&emsp;</td>
  <td>Specialty registrar in public health medicine, Kent County Council</td>
</tr>
<tr>
  <td>2023 to 2024</td>
  <td>&emsp;</td>
  <td>MSc in Public Health, London School of Hygiene and Tropical Medicine</td>
</tr>
<tr>
  <td>2022 to 2023</td>
  <td>&emsp;</td>
  <td>SHO and Lead NCHD, St James's Hospital, Dublin    </td>
</tr>
<tr>
  <td>2021 to 2022</td>
  <td>&emsp;</td>
  <td>Intern doctor, Health Service Executive, Ireland</td>
</tr>
<tr>
  <td>2016 to 2021</td>
  <td>&emsp;</td>
  <td>MB BCh BAO, Trinity College Dublin</td>
</tr>

</table>
